<?php

namespace Tests\Feature;

use App\Comment;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class commentTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        \Illuminate\Support\Facades\Artisan::call('migrate');
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testGetComments(){
        $comment = Comment::create(['content' => 'Salur']);
        $this->assertEquals(1, Comment::count());
    }
}
